import_path: login.LoginHandler
description: "Login a user using username/email and password authentication."
is_async: false
returns: true
depends_on:
  - name: db:mongo
    init: seed-login
signature:
  function: loginWithUsernameOrEmail
  parameters:
    - arg: 0
      type: string
      minimum: 3
      maximum: 64
    - arg: 1
      type: string
      minimum: 6
      maximum: 48

